services:
  - type: web
    name: inventory
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_NAME
        value: inventory_db
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: ""
